### ISSUE TITLE
dropping frames on shot asteroid collisions

### ISSUE THREAD

**Issue by AveryPratt** [AveryPratt/orbitroids#18]
The explodeAsteroid() function somehow changes the length of asteroids[] so that one of the iterations of the for loop has an undefined asteroid. Frame drops as a result.

stack trace:
    at checkShotAsteroidCollisions (http://127.0.0.1:8080/js/collisions.js:91:51)
    at checkCollisions (http://127.0.0.1:8080/js/app.js:179:3)
    at renderFrame (http://127.0.0.1:8080/js/app.js:374:7)

**Comment by AveryPratt** [comment]
solved!
I just needed to break out of the for loop that was testing the dead asteroid.
